[book]
authors = ["Alex Chi Z"]
language = "en"
src = "src"
title = "LSM in a Week"

[preprocessor.toc]
command = "mdbook-toc"
renderer = ["html"]

[output.html]
additional-css = ["custom.css"]
git-repository-url = "https://github.com/skyzh/mini-lsm"
